version: "3.4"
services:
  insurnace-api:
    image: insurance-api
    build:
      context: .
      dockerfile: Insurance/src/Insurance.Host/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - mongo-db
      - rabbitmq

  auditing-worker:
    image: auditing-worker
    build:
      context: .
      dockerfile: Auditing/src/Auditing.Host/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      sql-server-db:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
        
  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "testUser"
      MONGO_INITDB_ROOT_PASSWORD: "testPassword"  

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PStrong_password", "-Q", "select 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      MSSQL_SA_PASSWORD: "Strong_password"
      SQLCMDUSER: "sa"
      SQLCMDPASSWORD: "Strong_password"
      ACCEPT_EULA: "Y"
